### ISSUE TITLE
ROLL-30 : Profile page info from Firebase

### ISSUE THREAD

**Issue by brickgriff** [bgriffiniv/rollme#50]
Use one user as if it were logged in and display its information in the Profile page.

**Comment by brandlxee11** [comment]
"Within the card service, provide methods getCardsByOwner(uid:string):Card[], getCardsByHolder(uid:string):Card[], hasOwnedCards(uid:string):boolean, and hasHeldCards(uid:string:boolean)." Once a card is saved to firebase and reflects on the profile page, "new card" alert is no longer triggered.
